# Generated by Django 4.2.9 on 2024-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('instagram', models.CharField(max_length=25)),
                ('telegram', models.CharField(max_length=25)),
                ('whatsapp', models.CharField(max_length=25)),
            ],
        ),
    ]
